source/api_v1/urls.py
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import DefaultRouter
from api_v1.views import CommitViewSet

app_name = 'api_v1'

router = DefaultRouter()
router.register(r'commit', CommitViewSet)

urlpatterns = [
    path('', include(router.urls))
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from main import settings
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', include('webapp.urls')),
    path('api/v1/', include('api_v1.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import *

urlpatterns = [
    path('', IndexImageView.as_view(), name='index'),
    path('image/<int:pk>/', ImageDetailView.as_view(), name='image'),
    path('image/add/', ImageCreateView.as_view(), name='image_add'),
    path('image/<int:pk>/edit/', ImageUpdate.as_view(), name='update_image'),
    path('image/<int:pk>/delete/', ImageDelete.as_view(), name='delete_image'),

]

app_name = 'webapp'

source/api_v1/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Image(models.Model):
    image = models.ImageField(null=False, blank=False, upload_to='image_from_user', verbose_name='image')
    text = models.TextField(null=False, blank=False, verbose_name='text', max_length=2000)
    created_by = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE, verbose_name='user')
    like = models.IntegerField(default=0, verbose_name='like')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Time created')

    def __str__(self):
        return self.text


class Commit(models.Model):
    description = models.TextField(max_length=2000, null=False, blank=False, verbose_name='Description')
    created_by = models.ForeignKey(User, null=False, blank=False, verbose_name='created by',
                                   on_delete=models.PROTECT, related_name='created_by')
    image_for_comment = models.ForeignKey('webapp.Image', related_name='image_for_commit', on_delete=models.SET_NULL,
                                          verbose_name='image for commit', blank=False, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Time of add')

    def __str__(self):
        return self.description

source/webapp/forms.py
from django import forms
from webapp.models import Image


class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        exclude = ['created_at', 'created_by', 'like']

source/api_v1/views.py
from rest_framework.decorators import action
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from api_v1.serializers import CommitSerializer
from webapp.models import Image


class CommitViewSet(ModelViewSet):
    queryset = Image.objects.none()
    serializer_class = CommitSerializer

    def get_queryset(self):
        return Image.objects.all()

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)

    def get_permissions(self):
        if self.action not in ['update', 'partial_update', 'destroy']:
            return [AllowAny()]
        return [IsAuthenticated()]

    @action(methods=['post'], detail=True)
    def like_up(self, request, pk=None):
        like = self.get_object()
        like.like += 1
        like.save()
        return Response({'id': like.pk, 'like_up': like.like})

    @action(methods=['post'], detail=True)
    def like_down(self, request, pk=None):
        like = self.get_object()
        like.like -= 1
        like.save()
        return Response({'id': like.pk, 'like_down': like.like})

source/webapp/views.py
from django.http import HttpResponseRedirect
from django.urls.base import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from webapp.models import Image
from webapp.forms import ImageForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied


class IndexImageView(ListView):
    context_object_name = 'image'
    model = Image
    template_name = 'index.html'
    ordering = ['created_at']


class ImageDetailView(DetailView):
    model = Image
    template_name = 'image_detail.html'
    context_object_name = 'image'


class ImageCreateView(LoginRequiredMixin, CreateView):
    template_name = 'create.html'
    model = Image
    form_class = ImageForm
    raise_exception = PermissionDenied
    success_url = reverse_lazy('webapp:index')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:image', kwargs={'pk': self.object.pk})


class ImageUpdate(UserPassesTestMixin, UpdateView):
    model = Image
    form_class = ImageForm
    template_name = 'update.html'
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        image = Image.objects.filter(created_by__username=self.request.user, pk=self.kwargs['pk'])
        if image:
            return True


class ImageDelete(UserPassesTestMixin, DeleteView):
    template_name = 'delete.html'
    model = Image
    context_object_name = 'image'
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        image = Image.objects.filter(created_by__username=self.request.user, pk=self.kwargs['pk'])
        if image:
            return True

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Insta{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar">
   <div class="container">
       <ul class="menu">
        <li><a href="{% url 'webapp:index' %}" class="action-btn">home</a></li>
  {% if request.user.is_authenticated %}
                <li><a href="{% url 'logout'  %}" class="action-btn">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'login'  %}" class="action-btn">Log In</a></li>
                {% endif %}
           {% block menu %}{% endblock %}
       </ul>
   </div>
</nav>
<div class="container">
    <div class="for_margin">
    {% block content %}{% endblock %}
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script type="application/javascript" src="{% static "js/main.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/create.html
{% extends 'base.html' %}

{% block title %}Create image{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <h1>Create image</h1>
  <form method="POST" action="" class="for_form" enctype="multipart/form-data">
        {% include 'partial/image_form.html' with button_text='create' %}
    </form>
{% endblock %}

source/webapp/templates/delete.html
{% extends 'base.html' %}
{% block title %}Delete project{% endblock %}
{% block content %}
    <form method="POST" action="{% url 'webapp:delete_image' image.pk %}">{% csrf_token %}
        <h2>Are you sure you want to delete this project?</h2>
        <h3>image: {{ image.text }}</h3>
        <img class="avatar" src="{{ image.image.url }}" width="250" height="250" alt="user picture">
        <button type="submit" class="action-btn">Delete</button>
    </form>
{% endblock %}

source/webapp/templates/image_detail.html
{% extends 'base.html' %}

{% block title %}{{ image.text }}{% endblock %}

{% block menu %}

{% endblock %}

{% block content %}
    <h1>{{ image.text }}</h1>
        <img class="avatar" src="{{ image.image.url }}" width="250" height="250" alt="user picture">
    <h4>likes {{ image.like }}</h4>
    <p>time of creation {{ image.created_at }}</p>
    <hr/>
    <h3>Comments</h3>
        {% for commit in image.image_for_commit.all %}

            <div class="tracker_for_project">
                <h4>{{ commit.description }}</h4>
                <p class="comment-links">

                </p>
            </div>
        {% empty %}
            <p>No tracker yet.</p>
        {% endfor %}
{% endblock %}

source/webapp/templates/index.html
{% extends 'base.html' %}
{% block menu %}
    <li><a href="{% url 'webapp:image_add' %}" class="action-btn">add image</a></li>


{% endblock %}

{% block content %}
        <div class="home_div">
            {% for image_one in image %}
                <div class="boss_div">
                 <img class="avatar" src="{{ image_one.image.url }}" width="250" height="250" alt="user picture">
                    <h4>{{ image_one.text }}</h4>
                    <p id="rating_${item.id}">{{ image_one.like }}</p>
                {% if request.user.is_authenticated %}
                    <p><a href="" class="btn btn-success" onclick="rateUp({{ image_one.pk }})" id="{{ image_one.pk }}">+</a></p>
                    <p><a href="" class="btn btn-danger" onclick="rateDown({{ image_one.pk }})" id="{{ image_one.pk }}">-</a></p>
                {% endif %}
                    <div class="for_button">
                        <a href="{% url 'webapp:image' image_one.pk %}" class="btn btn1">More >>></a>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'webapp:update_image' image_one.pk %}"  class="btn btn3">Edit</a>
                            <a href="{% url 'webapp:delete_image' image_one.pk %}" class="btn btn2">Delete</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock %}

source/webapp/templates/partial/image_form.html
{% load widget_tweaks %}
{% csrf_token %}

{% for error in form.non_field_errors %}
   <p class="form-error">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}
        {% if field.field.required %}
            <span class="form-required">*</span>
        {% endif %}
        {% if field %}
        {% endif %}
    </label></p>
    {% if field.errors %}
        <p>{{ field|add_class:'field-error form-control' }}</p>
    {% else %}
        <p>{{ field|add_class:'form-control' }}</p>
    {% endif %}
    {% for error in field.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
{% endfor %}

<p class="text-center"><input type="submit" value="{{ button_text }}" class="btn btn-primary"></p>

source/webapp/templates/update.html
{% extends 'base.html' %}

{% block title %}Update image{% endblock %}
{% block menu %}
    <li><a href="{% url 'webapp:image' object.pk %}" class="action-btn">View</a></li>
{% endblock %}
{% block content %}
    <h1>Update image</h1>
    <form method="POST" action="{% url "webapp:update_image" object.pk %}" class="for_form">
        {% include 'partial/image_form.html' with button_text="edit" %}
    </form>
{% endblock %}